spring:
  datasource:
    username: root
    password: Mynewc@r123
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/JPA
#    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@10.211.55.3:1521:xe

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
#        dialect: org.hibernate.dialect.Oracle12cDialect




